name       : libvpx1
version    : 1.3.0
release    : 2
source     :
    - https://github.com/webmproject/libvpx/archive/v1.3.0.tar.gz : db72881e1c34e4ae92666847844f35dd2dd431bcf6284500b1b396464f882f64
license    : BSD-3-Clause
component  : binary.compat
emul32     : yes
summary    : libvpx1 (Binary Compatibility Library)
description: |
    This package provides binary compatibility only. It is forbidden to build against it.
builddeps  :
    - yasm
setup      : |
    %patch -p1 < $pkgfiles/gcc-5.patch
    %patch -p1 < $pkgfiles/security/cve-2017-13194.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ./configure --prefix=/usr --libdir=%libdir% --disable-static --enable-shared --target=x86-linux-gcc --disable-vp9
    else
        ./configure --prefix=/usr --libdir=%libdir% --disable-static --enable-shared --target=x86_64-linux-gcc --disable-vp9
    fi
build      : |
    %make
install    : |
    %make_install
    # Don't want this stuff in the snap
    for i in /usr/bin %libdir%/pkgconfig /usr/include %libdir%/libvpx.so; do
        rm -rfv "$installdir/$i"
    done
